### ISSUE TITLE
Amazon S3 Uploader Step Breaks on LTS Stack

### ISSUE THREAD

**Issue by mjones-droid** [scruffyfox/bitrise-amazon-s3-uploader#4]
Hey everyone! Just posting this in case others come here looking for help. 

At the moment we're aware that this step is broken on our Ubuntu LTS stack. This happened after we upgraded the version of the AWS-CLI to 1.18.69. Downgrading to the previous version (1.11.13) resolves the issue for now. 

We have a temporary workaround. Add the following into a script step before the s3 upload step:

```
apt-get remove awscli

curl "https://s3.amazonaws.com/aws-cli/awscli-bundle-1.11.13.zip" -o "awscli-bundle.zip" unzip awscli-bundle.zip sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
```

We're testing newer versions to see if they resolve the issue. If they do, we'll update the stack accordingly. 

Matthew
Senior Customer Engineer

**Comment by scruffyfox** [comment]
Thanks for the heads up! Ill try and see about making a fix for this

**Comment by sturman** [comment]
I have the same issue. Here are some details

**stack:** Android & Docker, on Ubuntu 16.04 - LTS Stack
**step:** Amazon S3 File uploader v1.0.1
**aws cli:**  aws-cli/1.18.69 Python/3.5.2 Linux/4.4.0-57-generic botocore/1.16.19
**error:**
```
Uploading file..._init_() got an unexpected keyword argument 'max_bandwidth'Failed to upload file
```
